school:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: smart-school
    username: postgres
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 10