school:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: smart-school
    username: root
    password: YuanRui20050614
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 10